// Mock data - 实际使用时替换为 OpenClaw API 调用
export const mockAgents = [
  {
    id: "main",
    name: "Ivy",
    emoji: "🧠",
    avatar: "IVY",
    status: "running",
    model: "claude-sonnet-4-6",
    currentTask: "处理飞书消息 · AI新闻摘要生成",
    startedAt: new Date(Date.now() - 1000 * 60 * 14),
    totalRuns: 1284,
    successRate: 98.2,
    channel: "feishu",
    description: "主助手 · 全能型",
    color: "#00ff88",
  },
  {
    id: "cron-news",
    name: "NewsBot",
    emoji: "📰",
    avatar: "NEWS",
    status: "idle",
    model: "claude-sonnet-4-6",
    currentTask: null,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 6),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 3),
    totalRuns: 42,
    successRate: 95.2,
    channel: "feishu",
    description: "每日AI新闻摘要 · 9:00 AM",
    color: "#00d4ff",
  },
  {
    id: "cron-portfolio",
    name: "PortfolioBot",
    emoji: "📈",
    avatar: "PORT",
    status: "idle",
    model: "claude-sonnet-4-6",
    currentTask: null,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
    totalRuns: 8,
    successRate: 100,
    channel: "feishu",
    description: "投资组合周报 · 周日 6:00 PM",
    color: "#ffd700",
  },
  {
    id: "cron-housing",
    name: "HouseBot",
    emoji: "🏠",
    avatar: "HOUSE",
    status: "idle",
    model: "claude-haiku-4-5",
    currentTask: null,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 24 * 0.5),
    totalRuns: 12,
    successRate: 91.7,
    channel: "feishu",
    description: "万科未来城房价监控 · 周一 9:00 AM",
    color: "#ff6b6b",
  },
  {
    id: "cron-learning",
    name: "LearnBot",
    emoji: "📚",
    avatar: "LEARN",
    status: "idle",
    model: "claude-sonnet-4-6",
    currentTask: null,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 3),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 21),
    totalRuns: 6,
    successRate: 100,
    channel: "feishu",
    description: "AI Agent 每日学习计划 · 6:00 AM",
    color: "#b388ff",
  },
  {
    id: "subagent-1",
    name: "ResearchAgent",
    emoji: "🔍",
    avatar: "RSCH",
    status: "error",
    model: "claude-sonnet-4-6",
    currentTask: "任务超时 · 技术Agent讨论",
    lastRun: new Date(Date.now() - 1000 * 60 * 30),
    totalRuns: 18,
    successRate: 83.3,
    channel: null,
    description: "临时子Agent · 按需启动",
    color: "#ff6b6b",
  },
];

export const systemStats = {
  totalAgents: 6,
  runningAgents: 1,
  idleAgents: 4,
  errorAgents: 1,
  totalTasksToday: 23,
  uptime: "99.2%",
};
